### PR TITLE
Use "delphix/actions/sync-with-upstream" action

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
This depends on https://github.com/delphix/actions/pull/5

**Comment by pzakha** [comment]
That looks interesting but don't we already have the linux-pkg update job performing the sync with master + building the package?

**Comment by prakashsurya** [comment]
> don't we already have the linux-pkg update job performing the sync with master + building the package?

Yes; this would replace that process. I presume you already expected that answer, so is there something else you're getting at with your question?

If you're wondering more about the design of using linux-pkg vs. actions, I prefer actions for the following reasons:

1. It reduces complexity by reducing the number of repositories involved; e.g. the configuration for syncing this repository with its upstream source is contained in this repository, rather than contained in a separate place. IMO, this makes things easier to understand, and easier to find and maintain (e.g. `git grep` is more useful).

2. It makes each repository more self-sufficient, and puts the maintenance/monitoring/etc. burden on the team responsible for the repository. IMO, this is a better design organizationally, rather than having a single maintainer (or rotation of maintainers, which we have today) bearing this responsibility for all repositories.

3. It enables us to rely less on Delphix managed infrastructure, and more on GitHub/Microsoft managed infrastructure. IMO, this is better since maintenance of our Delphix infra comes at a significant cost (in terms of people, hardware/software, reliability, onboarding/learning, etc), whereas we can get much of this for free by using externally managed infrastructure.

4. Additionally, while this isn't specific to linux-pkg vs. actions (since linux-pkg could do this as well), the new action opens a pull request rather than pushing directly to the downstream branch. IMO, this is better since it raises visibility about when the code changes (e.g. using pull request notifications, requiring 2 code reviews, etc.), but it also means we can leverage all the same pull request checks for testing as any other type of change (and enforce the checks pass).

**Comment by pzakha** [comment]
You may be aware that I'm working on a refactoring of linux-pkg that will include automatic ab-pre-push testing before merging the code automatically. It could be set-up to create pull requests instead of merging automatically for some repositories where we'd want to have more scrutiny, but otherwise it saves a lot of work to have it tested, merged and pushed automatically.

Regarding the maintenance burden for repositories, each package will have its own Jenkins job for building & updating, and we could redirect notifications to different channels if we feel like that is what we want.

So as of right now, I cannot approve this change as I think it would be a regression from the current & upcoming state of things. That said, I'm open for discussion on that matter, so we can figure out how we can improve things.

**Comment by prakashsurya** [comment]
>  as I think it would be a regression from the current & upcoming state of things.

Can you provide me with some specific examples of the regressions? I'd like think more about them in this alternate design I'm proposing.

> but otherwise it saves a lot of work to have it tested, merged and pushed automatically.

I can come up with a scheme that would automatically test and merge these PRs as well. I've thought about this already, but haven't done any prototyping.. but I don't think it'd be too difficult to have another action (or set of actions), that automatically merges these PRs after the tests pass.

> and we could redirect notifications to different channels if we feel like that is what we want.

Still, I doubt it'll be the same as what GitHub provides; personally (to put it lightly) I much prefer GitHub's notification system vs. what we've developed internally using Jenkins and Slack.

> You may be aware that I'm working on a refactoring of linux-pkg that will include automatic ab-pre-push testing before merging the code automatically.

If a specific repository requires testing that is not performed by `ab-pre-push`, how will we accomplish that?

For example, `delphix/sdb` has both style and functional tests that run on each PR, and it'd be ideal to run all these same tests when we update the repository via linux-pkg (I realize this is a bad example, since we don't have another upstream for `delphix/sdb`, but I think the idea/principle is still valid). Will it be possible to run GitHub Action based tests with your upcoming work?

Another example might be `delphix/zfs`, where we probably want to run our `zfs-precommit` suite prior to automatically syncing with upstream via `linux-pkg`. Will this be possible with your upcoming work?

**Comment by prakashsurya** [comment]
>  It could be set-up to create pull requests instead of merging automatically for some repositories where we'd want to have more scrutiny

FWIW, I do think it's important to enable the use of PR checks when doing automatic syncs with upstream. I say that because we're pushing for using Actions as the default way to write new tests for GitHub based repositories (e.g. see our GitHub best practices document), leveraging these for "pre push" testing wherever possible; so (IMO) we should also be able to leverage any Action based tests for upstream syncs.

**Comment by pzakha** [comment]
> Will it be possible to run GitHub Action based tests with your upcoming work?

Yeah, I'm pretty confident it should be possible, and even not that hard.

I propose we sync up on a call so that we can get on the same page. I can explain you what I have in mind for the improvements, and you can tell me more about your ideas for the use of GitHub actions for testing. I think we can combine out ideas to come up with something good.

**Pull request closed without merging**
